{{- if eq .Values.loadtest.locust_locustfile_configmap "zid-locustfile" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.loadtest.locust_locustfile_configmap }}
  labels:
{{ include "locust.labels" . | indent 4 }}
data:
{{ ($.Files.Glob (printf "locustfiles/%s/%s" "example" .Values.loadtest.locust_locustfile)).AsConfig | indent 2 }}
{{- end }}
