{{- if eq .Values.loadtest.locust_lib_configmap "zid-lib" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.loadtest.locust_lib_configmap }}
  labels:
{{ include "locust.labels" . | indent 4 }}
data:
{{ ($.Files.Glob (printf "locustfiles/%s/lib/*" "example")).AsConfig | indent 2 }}
{{- end }}
