on:
  push:
    branches:
      - main

name: Deploy LocustIO

jobs:
  build:
    - name: 'Deploy'
      uses: 'zidsa/helm@v1'
      if: steps.build-image.outputs.branch_name == 'main'
      with:
        release: '${{ github.event.repository.name }}'
        namespace: 'preview'
        chart: './'
        helm: 'helm3'
        token: '${{ github.token }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
